# Generated by Django 5.1.1 on 2025-06-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_description_post_published_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["status", "-created_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("published", "Опубликован"),
                    ("archived", "В архиве"),
                ],
                default="draft",
                help_text="Черновик — не виден на основном сайте",
                max_length=10,
                verbose_name="Статус публикации",
            ),
        ),
    ]
