# Generated by Django 5.1.1 on 2025-06-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_post_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["status", "-created_at"],
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="event_date",
            field=models.DateField(
                blank=True,
                help_text="Автоматически создаётся из сырого текста, если возможно",
                null=True,
                verbose_name="Дата события",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="event_date_raw",
            field=models.CharField(
                default="",
                help_text="Дата в формате '1 октября 1659 года'",
                max_length=100,
                verbose_name="Дата события (сырой текст)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.CharField(
                default="",
                help_text="Где происходит действие публикации",
                max_length=200,
                verbose_name="Местоположение",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status"], name="blog_post_status_02ce19_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-created_at"], name="post_created_desc"),
        ),
    ]
